Feature/homework4
polinamikhaylova1/ShiftHomeworks pull request #5
Opened 2024-05-09 10:18 UTC by polinamikhaylova1

Приложение с UICollectionView "Стартерпак на майские". 
Коллекция из 10 элементов "что берем с собой на пикник". Элемент содержит картинку и текст. Про каждый элемент есть детальная информация при нажатии. С экрана с детальной информацией модально открывается еще один экран.
Приложение поддерживает альбомную и портретную ориентации.

2024-05-11 14:44 UTC, rmaximov requested changes
Обрати внимание на гигиену кода - порядок переменных, методов в файле и заккоментированный код. Если что-то непонятно по комментариям - пиши в лс

2024-05-11 14:44 UTC, rmaximov commented on CollectionApp/CollectionApp.xcodeproj/xcuserdata/aleksandrasergeeva.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
> +<?xml version="1.0" encoding="UTF-8"?>
брейкпоинты можно не коммитить

2024-05-11 14:44 UTC, rmaximov commented on CollectionApp/CollectionApp/CollectionView.swift
> +                label.text = "Стартерпак на майские"
очень жеска в рабочее время читать про шашлыки 😔

2024-05-11 14:44 UTC, rmaximov commented on CollectionApp/CollectionApp/CollectionViewController.swift
> +    var collectionView: UICollectionView!
форс анврап стоит убрать и чутка причесать файл: переменные к перменным, методы к методам

2024-05-11 14:44 UTC, rmaximov commented on CollectionApp/CollectionApp/CollectionViewDataSource.swift
> +//    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
заккоментированный код

2024-05-11 14:44 UTC, rmaximov commented on CollectionApp/CollectionApp/CollectionViewDataSource.swift
> +        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: ItemCell.identifier, for: indexPath) as! ItemCell
форс каст к ItemCell

2024-05-11 14:44 UTC, rmaximov commented on CollectionApp/CollectionApp/ItemCell.swift
> +class ItemCell: UICollectionViewCell {
стоит давать более конкретные названия классам и файлам

2024-05-11 14:44 UTC, rmaximov commented on CollectionApp/CollectionApp/CollectionViewDataSource.swift
> +        self.navigationController = navigationController
не совсем понял, что тут делает navigationController

2024-05-11 14:44 UTC, rmaximov commented on CollectionApp/CollectionApp/CollectionViewDataSource.swift
> +    var items: [Item]
давай разделим доступ к данным и настройку датасорса

2024-05-11 14:44 UTC, rmaximov commented on CollectionApp/CollectionApp/Item.swift
> +    var imageName: String
нужна ли здесь мутабельность?

2024-05-11 14:44 UTC, rmaximov commented on CollectionApp/CollectionApp/ItemCell.swift
> +//            label.topAnchor.constraint(equalTo: imageView.bottomAnchor, constant: 8),
закомментированный код

2024-05-13 12:55 UTC, polinamikhaylova1 commented on CollectionApp/CollectionApp/CollectionViewDataSource.swift
> +        self.navigationController = navigationController
лишняя строчка

2024-05-13 13:00 UTC, rmaximov approved these changes

2024-05-19 09:16 UTC, merged